"""Groq (free tier, gpt-oss / llama / qwen / kimi / maverick) model definitions (seed data; DB CatalogModel takes precedence).

Extracted from the old monolithic models_data — identical entries, one file per provider.
LLM temperature is intentionally NOT part of any entry.
"""
from __future__ import annotations

from typing import Any, Dict, List

MODELS_GROQ: List[Dict[str, Any]] = [
    # -------------------- Groq provider models --------------------
    {
        "provider": "groq",
        "model_id": "openai/gpt-oss-120b",
        "prompt_cache": {"mode": "native_automatic"},
        "display_name": "GPT-OSS 120B",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.15,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.60,
        "context_window": 131072,
        "max_output_tokens": 32768,
        "reasoning_supported": True,
        "reasoning_default": "low",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "reasoning", "tools"],
        "notes": "Groq recommended, 120B reasoning, tool use.",
    },
    {
        "provider": "groq",
        "model_id": "openai/gpt-oss-20b",
        "prompt_cache": {"mode": "native_automatic"},
        "display_name": "GPT-OSS 20B",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.075,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.30,
        "context_window": 131072,
        "max_output_tokens": 32768,
        "reasoning_supported": True,
        "reasoning_default": "low",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "reasoning", "tools"],
        "notes": "Groq fast, 20B, lower TPM cost, good for voice.",
    },
    {
        "provider": "groq",
        "model_id": "openai/gpt-oss-safeguard-20b",
        "prompt_cache": {"mode": "native_automatic"},
        "display_name": "GPT-OSS Safeguard 20B (free)",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.075,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.3,
        "context_window": 131072,
        "max_output_tokens": 32768,
        "reasoning_supported": True,
        "reasoning_default": "low",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "safety"],
        "notes": "SAFETY-CLASSIFIER, not a chat model: fine-tuned for content moderation, replies are erratic as a receptionist and it tried to end_call on 'Ok.'. Use openai/gpt-oss-20b instead (same speed/price). Retired from pickers 2026-09-19.",
        "tier": "free",
        "status": "deprecated",
    },
    # -------------------- Groq provider models (current, post-Jun-2026 deprecations) --------------------
    # llama-3.1-8b-instant + llama-3.3-70b-versatile retired 2026-08-16
    # qwen/qwen3-32b + llama-4-scout retired 2026-07-17
    # -> replacements per Groq: openai/gpt-oss-20b, openai/gpt-oss-120b, qwen/qwen3.6-27b
    # Qwen3.6 27B -> Qwen3.8 27B swap 2026-09-24 (user request; Groq lists 3.8 as the
    # current Qwen: console.groq.com/docs/model/qwen/qwen3.8-27b). 3.6 stays callable
    # for agents that saved it explicitly, but is hidden from pickers as deprecated.
    {
        "provider": "groq",
        "model_id": "qwen/qwen3.8-27b",
        "display_name": "Qwen3.8 27B",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.8,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 4.0,
        "context_window": 131072,
        "max_output_tokens": 16384,
        "reasoning_supported": True,
        "reasoning_default": "none",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "reasoning", "tools", "vision"],
        "notes": "Free tier (rate-limited). Qwen3.6's successor on Groq: 27B dense, thinking/instruct dual mode (reasoning_effort none=default-for-voice; low/medium/high supported), vision (2048 tokens per image), ~450+ tps. Pricing $0.80/$4.00 per 1M — no prompt-cache discount, and Groq still rejects prompt_cache_key, so caching stays OpenAI-only.",
        "tier": "free",
    },
    {
        "provider": "groq",
        "model_id": "qwen/qwen3.6-27b",
        "display_name": "Qwen3.6 27B",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.6,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 3.0,
        "context_window": 131072,
        "max_output_tokens": 32768,
        "reasoning_supported": True,
        "reasoning_default": "none",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "deprecated", "free_tier": True,
        "capabilities": ["chat", "reasoning", "tools", "vision"],
        "notes": "Superseded by qwen/qwen3.8-27b (2026-09-24): hidden from pickers, still valid for agents that saved it explicitly. Free. Groq's former recommended Llama/Qwen3 replacement (27B dense, thinking mode); strong Hindi.",
        "tier": "free",
    },
    {
        "provider": "groq",
        "model_id": "meta-llama/llama-4-maverick-17b-128e-instruct",
        "display_name": "Llama 4 Maverick 17Bx128E",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.2,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.6,
        "context_window": 131072,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "tools", "vision"],
        "notes": "Free. Current Llama generation on Groq (llama-4-scout retired 2026-07-17). MoE, ~15 RPM free tier.",
        "tier": "free",
    },
    {
        "provider": "groq",
        "model_id": "moonshotai/kimi-k2-instruct",
        "display_name": "Kimi K2 Instruct",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 1.0,
        "cached_input_price_per_1m": 0.5,
        "output_price_per_1m": 3.0,
        "context_window": 262144,
        "max_output_tokens": 16384,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "tools"],
        "notes": "Free (60 RPM / 1k RPD on Groq). Strong reasoning & Hindi; 262k context swallows a full knowledge base.",
        "tier": "free",
    },
    {
        "provider": "groq",
        "model_id": "minimaxai/minimax-m2.7",
        "display_name": "MiniMax M2.7",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.6,
        "cached_input_price_per_1m": 0.3,
        "output_price_per_1m": 1.8,
        "context_window": 196608,
        "max_output_tokens": 16384,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active", "free_tier": True,
        "capabilities": ["chat", "tools"],
        "notes": "Free. 196k context; good multilingual instruction following.",
        "tier": "free",
    },
    {
        "provider": "groq",
        "model_id": "qwen/qwen3-32b",
        "display_name": "Qwen3 32B",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.10,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.40,
        "context_window": 131072,
        "max_output_tokens": 32768,
        "reasoning_supported": True,
        "reasoning_default": "none",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "deprecated",
        "capabilities": ["chat", "reasoning", "vision"],
        "notes": "Multimodal reasoning.",
    },
    {
        "provider": "groq",
        "model_id": "llama-3.3-70b-versatile",
        "display_name": "Llama 3.3 70B Versatile (deprecated)",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.59,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.79,
        "context_window": 131072,
        "max_output_tokens": 32768,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "tools"],
        "notes": "Deprecated by Groq 08/16/26, use gpt-oss models.",
    },
    {
        "provider": "groq",
        "model_id": "llama-3.1-8b-instant",
        "display_name": "Llama 3.1 8B Instant (deprecated)",
        "base_url": "https://api.groq.com/openai/v1",
        "input_price_per_1m": 0.05,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.08,
        "context_window": 131072,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "deprecated",
        "capabilities": ["chat", "tools"],
        "notes": "Deprecated by Groq 08/16/26.",
    },
]
