"""OpenRouter (deprecated — legacy agents only) model definitions (seed data; DB CatalogModel takes precedence).

Extracted from the old monolithic models_data — identical entries, one file per provider.
LLM temperature is intentionally NOT part of any entry.
"""
from __future__ import annotations

from typing import Any, Dict, List

MODELS_OPENROUTER: List[Dict[str, Any]] = [
    # -------------------- OpenRouter provider models --------------------
    {
        "provider": "openrouter",
        "model_id": "google/gemma-3-27b-it:free",
        "display_name": "Gemma 3 27B IT Free",
        "base_url": "https://openrouter.ai/api/v1",
        "input_price_per_1m": 0.0,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.0,
        "context_window": 131072,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "tools"],
        "notes": "Free tier rate-limited.",
    },
    {
        "provider": "openrouter",
        "model_id": "google/gemma-3-12b-it:free",
        "display_name": "Gemma 3 12B IT Free",
        "base_url": "https://openrouter.ai/api/v1",
        "input_price_per_1m": 0.0,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.0,
        "context_window": 32768,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "deprecated",
        "capabilities": ["chat", "tools"],
        "notes": "Free, lighter.",
    },
    {
        "provider": "openrouter",
        "model_id": "meta-llama/llama-3.3-70b-instruct:free",
        "display_name": "Llama 3.3 70B Instruct Free",
        "base_url": "https://openrouter.ai/api/v1",
        "input_price_per_1m": 0.0,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.0,
        "context_window": 131072,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "tools"],
        "notes": "Free tier.",
    },
    {
        "provider": "openrouter",
        "model_id": "qwen/qwen3-32b:free",
        "display_name": "Qwen3 32B Free",
        "base_url": "https://openrouter.ai/api/v1",
        "input_price_per_1m": 0.0,
        "cached_input_price_per_1m": 0.0,
        "output_price_per_1m": 0.0,
        "context_window": 131072,
        "max_output_tokens": 8192,
        "reasoning_supported": True,
        "reasoning_default": "none",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "deprecated",
        "capabilities": ["chat", "reasoning", "tools"],
        "notes": "Free reasoning.",
    },
]
