"""OpenAI (GPT-4.1 / GPT-4o / GPT-5 family) model definitions (seed data; DB CatalogModel takes precedence).

Extracted from the old monolithic models_data — identical entries, one file per provider.
LLM temperature is intentionally NOT part of any entry.
"""
from __future__ import annotations

from typing import Any, Dict, List

MODELS_OPENAI: List[Dict[str, Any]] = [

    # -------------------- OpenAI provider models --------------------
    {
        "provider": "openai",
        "model_id": "gpt-4.1",
        "display_name": "GPT-4.1",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 2.00,
        "cached_input_price_per_1m": 0.50,
        "output_price_per_1m": 8.00,
        "context_window": 1048576,
        "max_output_tokens": 32768,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "vision", "tools", "structured_output"],
        "notes": "1M context, strong instruction following, long-doc RAG.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-4.1-mini",
        "display_name": "GPT-4.1 Mini",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.40,
        "cached_input_price_per_1m": 0.10,
        "output_price_per_1m": 1.60,
        "context_window": 1048576,
        "max_output_tokens": 32768,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active",
        "capabilities": ["chat", "tools", "structured_output"],
        "notes": "Budget long-context, fast voice responses. Recommended for voice.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-4.1-nano",
        "display_name": "GPT-4.1 Nano",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.0,
        "cached_input_price_per_1m": 0.025,
        "output_price_per_1m": 0.40,
        "context_window": 1048576,
        "max_output_tokens": 32768,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "active",
        "capabilities": ["chat", "tools", "structured_output"],
        "notes": "Cheapest long-context, very fast.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-4o",
        "display_name": "GPT-4o",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 2.50,
        "cached_input_price_per_1m": 1.25,
        "output_price_per_1m": 10.00,
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "vision", "tools", "structured_output", "audio"],
        "notes": "Multimodal, legacy but still supported.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.0,
        "cached_input_price_per_1m": 0.075,
        "output_price_per_1m": 0.60,
        "context_window": 128000,
        "max_output_tokens": 16384,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active",
        "capabilities": ["chat", "vision", "tools", "structured_output"],
        "notes": "Cheap general chat.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-5",
        "display_name": "GPT-5",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 2.50,
        "cached_input_price_per_1m": 0.25,
        "output_price_per_1m": 15.00,
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_supported": True,
        "reasoning_default": "medium",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "reasoning", "tools", "structured_output"],
        "notes": "Flagship, unified knowledge + reasoning. Uses Responses API.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-5-mini",
        "display_name": "GPT-5 Mini",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.25,
        "cached_input_price_per_1m": 0.025,
        "output_price_per_1m": 2.00,
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_supported": True,
        "reasoning_default": "medium",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active",
        "capabilities": ["chat", "reasoning", "tools", "structured_output"],
        "notes": "GPT-5 budget, faster.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-5-nano",
        "display_name": "GPT-5 Nano",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.05,
        "cached_input_price_per_1m": 0.005,
        "output_price_per_1m": 0.40,
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_supported": True,
        "reasoning_default": "low",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "active",
        "capabilities": ["chat", "reasoning", "tools", "structured_output"],
        "notes": "Cheapest GPT-5, ultra fast.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-5.4",
        "display_name": "GPT-5.4",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 2.50,
        "cached_input_price_per_1m": 0.25,
        "output_price_per_1m": 15.00,
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_supported": True,
        "reasoning_default": "medium",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["chat", "reasoning", "tools", "structured_output"],
        "notes": "Current flagship, balanced.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-5.4-mini",
        "display_name": "GPT-5.4 Mini",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.25,
        "cached_input_price_per_1m": 0.025,
        "output_price_per_1m": 1.00,
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_supported": True,
        "reasoning_default": "medium",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "active",
        "capabilities": ["chat", "reasoning", "tools", "structured_output"],
        "notes": "Current budget, fast + cheap, good for voice.",
    },
    {
        "provider": "openai",
        "model_id": "gpt-5.4-nano",
        "display_name": "GPT-5.4 Nano",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 0.05,
        "cached_input_price_per_1m": 0.005,
        "output_price_per_1m": 0.40,
        "context_window": 400000,
        "max_output_tokens": 128000,
        "reasoning_supported": True,
        "reasoning_default": "low",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "very_fast",
        "status": "active",
        "capabilities": ["chat", "reasoning", "tools", "structured_output"],
        "notes": "Ultra budget, fastest.",
    },
    {
        "provider": "openai",
        "model_id": "o1",
        "display_name": "o1",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 15.00,
        "cached_input_price_per_1m": 7.50,
        "output_price_per_1m": 60.00,
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_supported": True,
        "reasoning_default": "high",
        "streaming_supported": True,
        "tool_calling_supported": False,
        "structured_output_supported": False,
        "expected_speed": "slow",
        "status": "deprecated",
        "capabilities": ["reasoning"],
        "notes": "Think-before-answering, slow, expensive.",
    },
    {
        "provider": "openai",
        "model_id": "o3-mini",
        "display_name": "o3 Mini",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 1.10,
        "cached_input_price_per_1m": 0.55,
        "output_price_per_1m": 4.40,
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_supported": True,
        "reasoning_default": "medium",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "medium",
        "status": "deprecated",
        "capabilities": ["reasoning", "tools"],
        "notes": "Fast reasoning.",
    },
    {
        "provider": "openai",
        "model_id": "o4-mini",
        "display_name": "o4 Mini",
        "base_url": "https://api.openai.com/v1",
        "input_price_per_1m": 1.10,
        "cached_input_price_per_1m": 0.275,
        "output_price_per_1m": 4.40,
        "context_window": 200000,
        "max_output_tokens": 100000,
        "reasoning_supported": True,
        "reasoning_default": "medium",
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": True,
        "expected_speed": "fast",
        "status": "deprecated",
        "capabilities": ["reasoning", "tools", "vision"],
        "notes": "Fast, cost-efficient reasoning.",
    },
]
