"""Sarvam AI (Indic) model definitions (seed data; DB CatalogModel takes precedence).

Extracted from the old monolithic models_data — identical entries, one file per provider.
LLM temperature is intentionally NOT part of any entry.
"""
from __future__ import annotations

from typing import Any, Dict, List

MODELS_SARVAM: List[Dict[str, Any]] = [
    # -------------------- Sarvam AI provider models --------------------
    {
        "provider": "sarvam",
        "model_id": "sarvam-30b",
        "display_name": "Sarvam 30B",
        "base_url": "https://api.sarvam.ai",
        "input_price_per_1m": 0.03012,
        "cached_input_price_per_1m": 0.01807,
        "output_price_per_1m": 0.12048,
        "context_window": 32768,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": False,
        "expected_speed": "very_fast",
        "status": "active",
        "capabilities": ["chat", "tools", "multilingual"],
        "notes": "⭐ Best pick when Bulbul TTS is also in use — purpose-built for Hindi/Hinglish. Prices are INR per 1M tokens (₹2.5 in / ₹1.5 cached / ₹10 out); set SARVAM_API_KEY.",
        "price_currency": "INR", "price_inr_per_1m": {"input": 2.5, "cached_input": 1.5, "output": 10.0}, "tier": "paid", "currency": "INR", "voice_recommended": True,
        "reasoning_effort_options": [],
    },
    {
        "provider": "sarvam",
        "model_id": "sarvam-30b-16k",
        "display_name": "Sarvam 30B 16k",
        "base_url": "https://api.sarvam.ai",
        "input_price_per_1m": 0.03012,
        "cached_input_price_per_1m": 0.01807,
        "output_price_per_1m": 0.12048,
        "context_window": 16384,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": False,
        "expected_speed": "very_fast",
        "status": "active",
        "capabilities": ["chat", "tools", "multilingual"],
        "notes": "Same rate as sarvam-30b with a 16k window. ₹2.5/₹1.5/₹10 per 1M.",
        "price_currency": "INR", "price_inr_per_1m": {"input": 2.5, "cached_input": 1.5, "output": 10.0}, "tier": "paid", "currency": "INR",
        "reasoning_effort_options": [],
    },
    {
        "provider": "sarvam",
        "model_id": "sarvam-105b",
        "display_name": "Sarvam 105B",
        "base_url": "https://api.sarvam.ai",
        "input_price_per_1m": 0.04819,
        "cached_input_price_per_1m": 0.03012,
        "output_price_per_1m": 0.19277,
        "context_window": 32768,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": False,
        "expected_speed": "fast",
        "status": "active",
        "capabilities": ["chat", "tools", "multilingual"],
        "notes": "Highest-quality Indic (₹4/₹2.5/₹16). Use only if 30B quality feels thin — slower than 30B for voice turns.",
        "price_currency": "INR", "price_inr_per_1m": {"input": 4.0, "cached_input": 2.5, "output": 16.0}, "tier": "paid", "currency": "INR",
        "reasoning_effort_options": [],
    },
    {
        "provider": "sarvam",
        "model_id": "sarvam-105b-32k",
        "display_name": "Sarvam 105B 32k",
        "base_url": "https://api.sarvam.ai",
        "input_price_per_1m": 0.04819,
        "cached_input_price_per_1m": 0.03012,
        "output_price_per_1m": 0.19277,
        "context_window": 32768,
        "max_output_tokens": 8192,
        "reasoning_supported": False,
        "reasoning_default": None,
        "streaming_supported": True,
        "tool_calling_supported": True,
        "structured_output_supported": False,
        "expected_speed": "fast",
        "status": "active",
        "capabilities": ["chat", "tools", "multilingual"],
        "notes": "32k-window variant of Sarvam 105B.",
        "price_currency": "INR", "price_inr_per_1m": {"input": 4.0, "cached_input": 2.5, "output": 16.0}, "tier": "paid", "currency": "INR",
        "reasoning_effort_options": [],
    },
]
